version: '3.9'

services:
  db:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    volumes:
      - .:/accounts
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/accounts_production"
      APP_ENV: "production"
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USERNAME: "your_email@gmail.com"
      SMTP_PASSWORD: "your_password"
      SMTP_DOMAIN: "arival.com"
    restart: on-failure
    stdin_open: true
    tty: true