version: '3.9'

services:
  db:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    volumes:
      - .:/accounts
    build: .
    command: sh -c "rake db:create && rake db:migrate && rackup --host 0.0.0.0 -p 4567"
    ports:
      - "4567:4567"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/accounts_production"
      APP_ENV: "production"
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USERNAME: "your_email@gmail.com"
      SMTP_PASSWORD: "your_password"
      SMTP_DOMAIN: "arival.com"
      POSTGRES_USER: postgres
      POSTGRES_PASS: password
    restart: on-failure
    stdin_open: true
    tty: true
  
  test:
    volumes:
      - .:/accounts
    build: .
    command: sh -c "APP_ENV=test rake db:create && rake db:migrate && rspec spec"
    ports:
      - "4568:4567"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/accounts_test"
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
      APP_ENV: "test"
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USERNAME: "your_email@gmail.com"
      SMTP_PASSWORD: "your_password"
      SMTP_DOMAIN: "arival.com"
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "password"
      POSTGRES_HOST: db
    restart: on-failure
    stdin_open: true
    tty: true
