development:
  adapter: postgresql
  encoding: unicode
  database: accounts_development
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: accounts_development
  pool: 5
  username: postgres
  password: postgres